### PR TITLE
Update Order and CustomerSearch

### PR DESCRIPTION
**Pull request by adamelfstrom**
New params and fields from API docs

### CODE REVIEW

**Comment by adamelfstrom** [comment]
@richardrandak

**Review by richardrandak — APPROVED** [review]

**Comment by richardrandak** [comment]
Looks like there are some policies now which requires two approves. @adamelfstrom are you able to change that?

**Comment by adamelfstrom** [comment]
@richardrandak No I don't think so. I was automatically removed as a maintainer from the repo by some new policies recently (perhaps at the same time as the double reviewer one was added). I think they are applied to all Fortnox repos, and I got no heads-up about it. If you can invite me again that would be great.

**Comment by richardrandak** [comment]
Well, I was also removed from Fortnox and invited just as a contributor, so can't do much about this now.. maybe you can contact Fortnox or eventually move the repository under Softwerk?

**Comment by adamelfstrom** [comment]
Hm ok, that's a bummer.  I'll check what we can do.

**Pull request merged**
