### PR TITLE
Update fortnox rate limits to latest version.

### PR DESCRIPTION
**Pull request by itstodSiik**
Fortnox has changed the way they handle the ratelimits for the API. Suggested changes gets the SDK in line with new standards.

### CODE REVIEW

**Comment by andersjerenvik** [comment]
https://developer.fortnox.se/blog/fortnox-will-raise-its-api-rate-limit-and-make-changes-to-the-current-sliding-window/

**Comment by richardrandak** [comment]
Seems like the limit change was not yet applied on the server.. I am getting TooManyRequest errors now.

**Comment by andersjerenvik** [comment]
@richardrandak 

The change is applied but the problem is that the ratelimiter doesn't handle the sliding window.

Please change the values to 5 requests per second instead.

**Comment by richardrandak** [comment]
I made a test to send 100 requests.. it fails even with the rate limiter set to 5 per 1 second. It does not fail with rate limiter set to 4 per 1 second..

**Comment by andersjerenvik** [comment]
We tried 1 per 0,2 second and that seems to work. Maybe thats the best implementation at the moment?

**Comment by richardrandak** [comment]
There might be a problem that the existing access tokens has still the old rate limit applied. I was trying with the one I am using in the tests. So, this is true at least for the static auth tokens.

I made a new app and generated the standard auth token and the 5 request / 1 second works fine.

I will have to check with support how this actually work for existing tokens. For back-compatibility, I might have to make the rate limiter configurable.

**Pull request merged**
