### PR TITLE
Remove ReadOnly attribute from Article.SalesPrice

### PR DESCRIPTION
**Pull request by WilliamGanrot**
I don't see any reason for the attribute [ReadOnly] on property Article.SalesPrice since the field is accessable directly through the API.

If the Attribute has to stay on the property please explain.

If the pr is accepted I would appriciate if you could do a release as soon as possible :)  

Thanks

### CODE REVIEW

**Comment by richardrandak** [comment]
Hello William!
The reason for this is that it was marked as read-only in the [old documentation](https://developer.fortnox.se/documentation/resources/articles/).
Support_Screenshot

I also tried to update the property just now in Postman and it really is read-only, giving BadRequest in case it is sent in JSON.

What is your motivation for removing it? :)

**Comment by WilliamGanrot** [comment]
Hi!

We are working on an integration to Fortnox and need to be able to create an article, where the SalesPrice is a pretty vital property :)

I'm asuming that it's a bug in the API and the field should actually be writable since it's writable according to the documentation? If my assumption is correct do you think that is something that could be fixed?  It's kind of crucial for us to be able to write to the field.

Thank you!

**Comment by richardrandak** [comment]
In which documentation is the SalesPrice write-able? I don't think it is a bug.

To change a price of an article, you have to update Price entity. 
I am not very familiar with price lists, but i tried just now, in my case, the SalesPrice is equal to a price in price list "A" for that article. So, when I updated a price in price list A, the SalesPrice on article changed as well.

So, check the PriceConnector

**Comment by WilliamGanrot** [comment]
It looks like it's writable according to [this documentation](https://developer.fortnox.se/documentation/resources/articles/#Create-an-article) since they pass a SalesPrice in the CURL example for creating an article. But yes, you are correct, if I scroll down I can in fact see that the SalesPrice is ReadOnly.

I will look in to the PriceConnector.
Thanks for the help!

**Comment by richardrandak** [comment]
In the CURL request they only specified ArticleNumber and Description. The SalesPrice is in response json :)
Anyway, good luck, let me know if you run in any other issues.

**Pull request closed without merging**
