### PR TITLE
Update example to use new authorization

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by richardrandak** [comment]
I would prefer not putting there the call for token refresh.. the details about the auth workflow can be found in the wiki document.

**Comment by vanillajonathan** [comment]
Then we should remove the legacy code and link to the wiki I guess.

**Comment by richardrandak** [comment]
hmm... i think a simple example on the main page was good. Why not keep it just with the new authorization instead of the legacy one?

``` csharp
var authorization = new StandardAuth(tokenInfo.AccessToken);
var client = new FortnoxClient(authorization);

var customer = new Customer()
{
    CustomerNumber = "1",
    Name = "Stefan Andersson"
};

customer = await client.CustomerConnector.CreateAsync(customer);
```

**Comment by vanillajonathan** [comment]
Yes, I also liked the idea of having an example on the main page, but the access tokens are short lived so I believe a proper example would obtain a refresh token.

**Comment by richardrandak** [comment]
The example at main page has just representative purpose to show the general purpose of the SDK, not necessary a "proper" one. I would prefer to not bother the potential user with the authentication there. For that he has the wiki page.

**Pull request merged**
