### PR TITLE
Add static class with all predefined accounts

### PR DESCRIPTION
**Pull request by bpaolo71**

### CODE REVIEW

**Comment by bpaolo71** [comment]
It should work now

**Comment by richardrandak** [comment]
Could you rename the folder from "Predefined Accounts" to something like "Constants"?

**Comment by richardrandak** [comment]
Sorry, I see the folder was already there :) ..I just don't like the namespace with underscore. Can you please remove the "Predefined_Accounts" part and let it simply reside in Entities namespace?

**Comment by bpaolo71** [comment]
Of course. I didn't realize this before you told me :)

**Comment by bpaolo71** [comment]
It looks like there are tests that fail but they are not related to this specific pull request.

**Pull request merged**
