### PR TITLE
Add `paymentpending` filtering option for SupplierInvoices

### PR DESCRIPTION
**Pull request by seckin206**
Seems like it is forgotten to be implemented.

### CODE REVIEW

**Comment by davidulvmoen** [comment]
Thank you! However, there are a number of things we are currently trying to fix on this resourse...

**Comment by seckin206** [comment]
@davidulvmoen 
What is the schedule on those fixes? Is there any way we can track the progress?

**Comment by davidulvmoen** [comment]
This amongst other fetures, will go into our next release that is coming probably next week. You can find a little bit more information in our (visible) backlog that is located under projects. You might also see a dev/branch in the future.

**Comment by seckin206** [comment]
Thank you very much for the info @davidulvmoen. Good luck for the upcoming release!

**Pull request closed without merging**
